recipes-bsp: imx-mkimage: fix corrupted patch
When building Variscite's U-Boot manually, trying to apply
'0002-iMX8M-soc-change-padding-of-DDR4-and-LPDDR4-DMEM-fir.patch'
to imx-mkimage, branch lf-6.1.36_2.1.0, using 'git apply' would
result in the following error:
  error: corrupt patch at line 29

Fix the patch to apply it cleanly, by doing the following:
  git clone https://github.com/nxp-imx/imx-mkimage -b lf-6.1.36_2.1.0
  apply the 0002-iMX8M-soc-change-padding-of-DDR4-and-LPDDR4-DMEM-fir.patch
    changes to iMX8M/soc.mak, manually.
  replace the content of 0002-iMX8M-soc-change-padding-of-DDR4-and-LPDDR4-DMEM-fir.patch
    by the output of 'git diff' after the changes are made.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>