imx8qm-var-som: conf: remove nxpiw612-sdio from MACHINE_FEATURES
Derived from commit 4ad4d2d309ab.

Remove nxpiw612-sdio from MACHINE_FEATURES to prevent including
'iw612-utils' [1] to boards where it is not compatible [2],
resulting in the following error:

ERROR: Nothing RPROVIDES 'iw612-utils'
  (but packagegroup-base.bb RDEPENDS on or otherwise requires it)
iw612-utils was skipped: incompatible with machine imx8mn-var-som
  (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'iw612-utils' is unbuildable, removing...
Missing or unbuildable dependency chain was:
  ['var-recovery-image', 'packagegroup-base-extended', 'iw612-utils']

[1] https://github.com/varigit/meta-variscite-bsp-imx/blob/e9484511d1c8/conf/machine/variscite.inc#L84
[2] https://github.com/varigit/meta-variscite-bsp-common/blob/1c3152af48bc/recipes-connectivity/iw612-utils/iw612-utils.bb#L40

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>