isp-imx: add recipe aligned to NXP kirkstone-5.15.52-2.1.0
Fixes the following errors:
ERROR: isp-imx-4.2.2.19.0-r0 do_fetch: Fetcher failure for URL: 'https://www.nxp.com/lgfiles/NMG/MAD/YOCTO//isp-imx-4.2.2.19.0.bin;fsl-eula=true'. Checksum mismatch!
File: '/opt/Yocto/downloads/isp-imx-4.2.2.19.0.bin' has md5 checksum '01f83394df91091f414f122c339c02bc' when 'd0350ad40df96a84efc4802975f92c91' was expected
File: '/opt/Yocto/downloads/isp-imx-4.2.2.19.0.bin' has sha256 checksum 'ab65a413f397230010266579df570beac5fde4af430e31fc251d7cf7c8fa2232' when '5544aef41546906bc4999de1980e4706cf241c93732633efde57b018ac4863c3' was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[sha256sum] = "ab65a413f397230010266579df570beac5fde4af430e31fc251d7cf7c8fa2232"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.
ERROR: isp-imx-4.2.2.19.0-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://www.nxp.com/lgfiles/NMG/MAD/YOCTO//isp-imx-4.2.2.19.0.bin;fsl-eula=true')
ERROR: Logfile of failure stored in: /home/ff/ssd-dev/var/yocto/kirkstone.1/build_xwayland.mp/tmp/work/armv8a-mx8mp-fslc-linux/isp-imx/4.2.2.19.0-r0/temp/log.do_fetch.169030
ERROR: Task (/home/ff/ssd-dev/var/yocto/kirkstone.1/sources/meta-freescale/recipes-bsp/isp-imx/isp-imx_4.2.2.19.0.bb:do_fetch) failed with exit code '1'

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>