wl18xx-calibrator: drop dependency from wl18xx-fw
This revert part of the patch aef8eaa fixing the following compilation errors:

  ERROR: Nothing RPROVIDES 'wl18xx-fw' (but /home/ff/ssd-dev/var/yocto/kirkstone/sources/meta-variscite-bsp/recipes-connectivity/wl18xx-calibrator/wl18xx-calibrator_8.7.3.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'wl18xx-fw' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['wl18xx-fw']
  NOTE: Runtime target 'wl18xx-calibrator' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['wl18xx-calibrator', 'wl18xx-fw']
  NOTE: Runtime target 'packagegroup-base-extended' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-base-extended', 'wl18xx-calibrator', 'wl18xx-fw']
  ERROR: Required build target 'fsl-image-gui' has no buildable providers.
  Missing or unbuildable dependency chain was: ['fsl-image-gui', 'packagegroup-base-extended', 'wl18xx-calibrator', 'wl18xx-fw']

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>