EULA.txt, layer.conf: Updated to license version 34
This patch fixes the following bitbake compilation error:
"A valid package EULA with md5sum in [...] was not found ..."

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>